version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    container_name: ahmed-amin-frontend
    environment:
      - NODE_ENV=production
    volumes:
      - ./ssl:/etc/nginx/ssl:ro
      - ./nginx-ssl.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - certbot

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./ssl:/etc/letsencrypt
      - ./webroot:/var/www/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --email admin@deepthinkcodearts.com --agree-tos --no-eff-email -d ahmedamin.deepthinkcodearts.com